
    let excludedNames=[];
    const categoryNames=['食物','飲料','雜貨','交通','娛樂','生活','房租','學費','其他'];
    const paths={食物:'M4 3v7a3 3 0 0 0 3 3v8M7 3v7M10 3v7a3 3 0 0 1-3 3M16 3v18M16 3c3 2 4 5 4 8h-4',飲料:'M7 3h10l-1 18H8L7 3Zm1 5h8m-5-5 4 5',雜貨:'M3 4h2l2 11h10l2-8H6m2 12h.01M17 19h.01',交通:'M5 16V6c0-2 2-3 7-3s7 1 7 3v10M5 11h14M7 20l2-4m8 4-2-4M8 7h8',娛樂:'M4 6h16v12H4zM8 10h.01M16 10h.01m-7 4c2 2 4 2 6 0',生活:'M4 10 12 3l8 7v10h-6v-6h-4v6H4z',房租:'M3 21h18M5 21V8l7-5 7 5v13M9 12h6',學費:'m3 10 9-5 9 5-9 5-9-5Zm4 2v5c3 2 7 2 10 0v-5',其他:'M5 12h.01M12 12h.01M19 12h.01',收入:'M12 3v18m-5-5 5 5 5-5M7 8l5-5 5 5'};
    const icon=name=>'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+(paths[name]||paths.其他)+'"/></svg>';
    const color={食物:'#f5a623',飲料:'#06b6d4',雜貨:'#8b5cf6',交通:'#ec4899',娛樂:'#f97316',生活:'#10b981',房租:'#64748b',學費:'#3b82f6',其他:'#6b7280',收入:'#22a854'};
    const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);document.documentElement.classList.toggle('ios',isIOS);
    let transactions=[];
    let mode='expense',tab='detail',period='month',paymentFilter='all',pendingPayment='all',categoryFilter=null;
    let anchorDate=new Date(),customRange={start:new Date(2026,8,3,12),end:new Date(2026,8,16,12)};
    const content=document.querySelector('#content'),seg=document.querySelector('#seg'),back=document.querySelector('#backdrop'),pop=document.querySelector('#popover'),filterPanel=document.querySelector('#filterPanel');
    const money=n=>'$'+n.toLocaleString('en-US');
    const dateLabel=d=>{const [y,m,day]=d.split('-');return `${+m}月<br>${+day}`};
    const dateFromKey=key=>new Date(key+'T12:00:00');
    const keyOf=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
    const todayKey=()=>keyOf(new Date());
    const displayDate=key=>{if(!key)return '選擇日期';const date=dateFromKey(key);return `${date.getFullYear()}年${date.getMonth()+1}月${date.getDate()}日`};
    const addDays=(date,n)=>{const next=new Date(date);next.setDate(next.getDate()+n);return next};
    const startOfWeek=date=>{const next=new Date(date);const offset=(next.getDay()+6)%7;next.setDate(next.getDate()-offset);next.setHours(12,0,0,0);return next};
    function activeRange(){if(period==='week'){const start=startOfWeek(anchorDate);return {start,end:addDays(start,6)}}if(period==='month'){const start=new Date(anchorDate.getFullYear(),anchorDate.getMonth(),1,12);return {start,end:new Date(anchorDate.getFullYear(),anchorDate.getMonth()+1,0,12)}}if(period==='year'){return {start:new Date(anchorDate.getFullYear(),0,1,12),end:new Date(anchorDate.getFullYear(),11,31,12)}}return customRange}
    function inPeriod(tx){const {start,end}=activeRange(),date=dateFromKey(tx.date);return date>=start&&date<=end}
    function selected(){return transactions.filter(tx=>inPeriod(tx)&&(paymentFilter==='all'||tx.payment===paymentFilter))}
    function currentList(){return selected().filter(tx=>tx.type===mode&&(!categoryFilter||tx.category===categoryFilter)).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id)}
    const rangeDateText=date=>`${date.getFullYear()}/${date.getMonth()+1}/${date.getDate()}`;
    function rangeText(){const {start,end}=activeRange();return `${rangeDateText(start)} – ${rangeDateText(end)}`}
    function shiftedRange(direction){const {start,end}=activeRange();if(period==='week')return {start:addDays(start,direction*7),end:addDays(end,direction*7)};if(period==='month')return {start:new Date(start.getFullYear(),start.getMonth()+direction,1,12),end:new Date(start.getFullYear(),start.getMonth()+direction+1,0,12)};if(period==='year')return {start:new Date(start.getFullYear()+direction,0,1,12),end:new Date(start.getFullYear()+direction,11,31,12)};const span=Math.round((end-start)/86400000)+1;return {start:addDays(start,direction*span),end:addDays(end,direction*span)}}
    function shiftRange(direction){if(period==='week')anchorDate=addDays(anchorDate,direction*7);else if(period==='month')anchorDate=new Date(anchorDate.getFullYear(),anchorDate.getMonth()+direction,15,12);else if(period==='year')anchorDate=new Date(anchorDate.getFullYear()+direction,anchorDate.getMonth(),15,12);else customRange=shiftedRange(direction)}
    function renderHeader(){document.querySelector('#currentRange').textContent=rangeText();const prev=shiftedRange(-1),next=shiftedRange(1),{start,end}=activeRange(),today=dateFromKey(todayKey());document.querySelector('#prev').textContent=rangeDateText(prev.end);document.querySelector('#next').textContent=rangeDateText(next.start);document.querySelector('#prev').setAttribute('aria-label','上一個'+period+'區間：'+rangeDateText(prev.start)+'至'+rangeDateText(prev.end));document.querySelector('#next').setAttribute('aria-label','下一個'+period+'區間：'+rangeDateText(next.start)+'至'+rangeDateText(next.end));document.querySelector('#todayRange').hidden=today>=start&&today<=end;const all=selected();const income=all.filter(x=>x.type==='income').reduce((s,x)=>s+x.amount,0),expense=all.filter(x=>x.type==='expense').reduce((s,x)=>s+x.amount,0);document.querySelector('.summary-card.income .amount').textContent=money(income);document.querySelector('.summary-card.expense .amount').textContent=money(expense)}
    function transactionRow(x){return '<button class="tx" data-tx-id="'+x.id+'" ><div class="date">'+dateLabel(x.date)+'</div><div><div class="cat">'+escapeHTML(x.category)+'</div><div class="tx-name">'+escapeHTML(x.name)+'</div><div class="meta"><span class="badge">手動</span><span>'+escapeHTML(x.payment)+'</span></div></div><div class="tx-amount '+(x.type==='income'?'income':'')+'">'+(x.type==='income'?'+':'-')+money(x.amount)+'</div></button>'}
    function detailHTML(list){const groups={};list.forEach(x=>(groups[x.date.slice(0,7)]??=[]).push(x));let html='<h2 class="section-title">'+(categoryFilter?categoryFilter:(mode==='expense'?'支出':'收入'))+'明細</h2>';for(const [key,rows] of Object.entries(groups)){html+='<div class="month-title">'+key.replace('-',' 年 ')+' 月</div><div class="rows">'+rows.map(transactionRow).join('')+'</div>'}return html+(list.length?'':'<p style="text-align:center;color:var(--muted);padding:36px">此區間沒有紀錄</p>')}
    function categoryHTML(list){const groups={};list.forEach(x=>{const g=groups[x.category]??={amount:0,count:0};g.amount+=x.amount;g.count++;groups[x.category]=g});const chartGroups=Object.entries(groups).filter(([name])=>!excludedNames.includes(name));const total=Math.max(1,chartGroups.reduce((s,[,x])=>s+x.amount,0));let html='<h2 class="section-title">'+(mode==='expense'?'支出':'收入')+'分類</h2>'+(mode==='expense'?'<div class="excluded-note">消費占比已排除：'+excludedNames.map(escapeHTML).join('、')+'</div>':'')+'<div class="cat-list">';for(const [name,x] of Object.entries(groups).sort((a,b)=>b[1].amount-a[1].amount)){const excluded=mode==='expense'&&excludedNames.includes(name),pct=excluded?0:Math.round(x.amount/total*1000)/10;html+='<button class="category" data-category-detail="'+escapeHTML(name)+'"><div class="cat-icon" style="background:'+color[name]+'">'+icon(name)+'</div><div><span class="cat-name">'+escapeHTML(name)+'</span><span class="count">'+x.count+' 筆明細'+(excluded?'・不列入圖表':'')+'</span></div><div class="cat-amount '+(mode==='income'?'income':'')+'">'+(mode==='income'?'+':'-')+money(x.amount)+'</div><div class="barline"><span class="percent">'+(excluded?'排除':pct+'%')+'</span><div class="track"><div class="fill" style="width:'+pct+'%;background:'+(mode==='income'?'var(--success)':'var(--accent2)')+'"></div></div></div></button>'}return html+(list.length?'':'<p style="text-align:center;color:var(--muted);padding:36px">此區間沒有資料</p>')+'</div>'}
    class Spring{constructor(stiffness,damping,value){this.k=stiffness;this.c=damping;this.value=value;this.target=value;this.velocity=0;this.last=0;this.raf=0}setTarget(target){this.target=target;if(!this.raf){this.last=performance.now();this.raf=requestAnimationFrame(t=>this.step(t))}}step(now){const dt=Math.min(.032,(now-this.last)/1000);this.last=now;const a=this.k*(this.target-this.value)-this.c*this.velocity;this.velocity+=a*dt;this.value+=this.velocity*dt;document.querySelector('.seg-indicator').style.transform=`translateX(${this.value*100}%)`;if(Math.abs(this.target-this.value)<.001&&Math.abs(this.velocity)<.01){this.value=this.target;this.velocity=0;document.querySelector('.seg-indicator').style.transform=`translateX(${this.value*100}%)`;this.raf=0;return}this.raf=requestAnimationFrame(t=>this.step(t))}}
    const segmentSpring=new Spring(220,20,1);
    function renderControlState(){document.querySelectorAll('.seg button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));segmentSpring.setTarget(tab==='detail'?1:0);document.querySelectorAll('.range-btn').forEach(b=>b.classList.toggle('active',b.dataset.period===period));const state=document.querySelector('#filterState');state.innerHTML=(paymentFilter==='all'?'':'<button class="filter-chip" id="clearFilterChip">帳戶：'+escapeHTML(paymentFilter)+' <span class="close-chip">×</span></button>')+(categoryFilter?'<button class="filter-chip" id="clearCategoryChip">分類：'+escapeHTML(categoryFilter)+' <span class="close-chip">×</span></button>':'');const chip=document.querySelector('#clearFilterChip');if(chip)chip.onclick=()=>{paymentFilter='all';pendingPayment='all';render();toast('已顯示全部帳戶')};const categoryChip=document.querySelector('#clearCategoryChip');if(categoryChip)categoryChip.onclick=()=>{categoryFilter=null;render()}}
    function render(){renderHeader();renderControlState();content.innerHTML=tab==='detail'?detailHTML(currentList()):categoryHTML(currentList());document.querySelectorAll('[data-category-detail]').forEach(button=>button.onclick=()=>{categoryFilter=button.dataset.categoryDetail;tab='detail';seg.dataset.tab=tab;render()})}
    let editingId=null,formType='expense',formCategory='食物',formTip=0,formItems=[];
    const pinnedSuggestions=new Set(),hiddenSuggestions=new Set();
    const normalizeName=value=>value.trim().toLocaleLowerCase('zh-Hant').replace(/[\s・·—–_-]+/g,'');
    const escapeHTML=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
    function nameSimilarity(a,b){if(!a||!b)return 0;if(a.includes(b)||b.includes(a))return .9;const aa=new Set([...a]),bb=new Set([...b]);let hit=0;aa.forEach(char=>{if(bb.has(char))hit++});return hit/Math.max(aa.size,bb.size)}
    function renderCategories(){document.querySelector('#categoryGrid').innerHTML=categoryNames.map(name=>'<button class="category-choice '+(name===formCategory?'active':'')+'" data-category="'+escapeHTML(name)+'"><span style="background:'+color[name]+'">'+icon(name)+'</span>'+escapeHTML(name)+'</button>').join('');document.querySelectorAll('.category-choice').forEach(b=>b.onclick=()=>{formCategory=b.dataset.category;renderCategories();renderSuggestions()})}
    function renderSuggestions(){const q=normalizeName(document.querySelector('#newName').value),amount=Number(document.querySelector('#newAmount').value),groups=new Map();transactions.filter(x=>x.type===formType&&x.category===formCategory&&x.name).forEach(tx=>{const key=normalizeName(tx.name);if(hiddenSuggestions.has(key))return;const group=groups.get(key)||{key,count:0,tx};group.count++;if(tx.date>group.tx.date||(tx.date===group.tx.date&&tx.id>group.tx.id))group.tx=tx;groups.set(key,group)});const matches=[...groups.values()].map(group=>{const similarity=nameSimilarity(group.key,q),txAmount=Number(group.tx.subtotal??group.tx.amount),priceMatch=amount>0&&Math.abs(txAmount-amount)<.01;return {...group,similarity,priceMatch,score:(pinnedSuggestions.has(group.key)?1000:0)+group.count*20+(priceMatch?180:0)+(q?similarity*150:0)+Number(group.tx.date.replaceAll('-',''))/10000000}}).filter(group=>!q||group.similarity>=.34||group.priceMatch).sort((a,b)=>b.score-a.score).slice(0,4);document.querySelector('#suggestions').innerHTML=matches.map(group=>{const x=group.tx,reason=group.priceMatch?'同價格':group.count>1?`買過 ${group.count} 次`:'最近使用';return `<div class="suggestion-card"><button class="suggestion" data-suggestion="${x.id}"><span>${escapeHTML(x.name)}</span><small><span class="suggestion-reason">${reason}</span>・${money(x.subtotal??x.amount)}・${escapeHTML(x.payment)}</small></button><button class="suggestion-tools ${pinnedSuggestions.has(group.key)?'pinned':''}" data-pin-suggestion="${escapeHTML(group.key)}" aria-label="釘選推薦">★</button><button class="suggestion-tools" data-hide-suggestion="${escapeHTML(group.key)}" aria-label="移除推薦">×</button></div>`}).join('');document.querySelectorAll('[data-suggestion]').forEach(button=>button.onclick=()=>{const x=transactions.find(tx=>tx.id==button.dataset.suggestion);document.querySelector('#newName').value=x.name;document.querySelector('#newAmount').value=x.subtotal??x.amount;document.querySelector('#newPayment').value=x.payment;formTip=x.tipPercent||0;formItems=(x.items||[]).map(item=>({...item}));document.querySelectorAll('#tipChips button').forEach(chip=>chip.classList.toggle('active',+chip.dataset.tip===formTip));renderItems();updateTotal()});document.querySelectorAll('[data-pin-suggestion]').forEach(button=>button.onclick=()=>{const key=button.dataset.pinSuggestion;pinnedSuggestions.has(key)?pinnedSuggestions.delete(key):pinnedSuggestions.add(key);renderSuggestions()});document.querySelectorAll('[data-hide-suggestion]').forEach(button=>button.onclick=()=>{hiddenSuggestions.add(button.dataset.hideSuggestion);renderSuggestions()})}
    function renderItems(){document.querySelector('#itemList').innerHTML=formItems.map((item,i)=>'<div class="item-row"><input data-item-name="'+i+'" placeholder="品名" value="'+escapeHTML(item.name||'')+'"><input data-item-price="'+i+'" inputmode="decimal" placeholder="價格可空白" value="'+(item.amount??'')+'"><button data-remove-item="'+i+'">×</button></div>').join('');document.querySelectorAll('[data-item-name]').forEach(el=>el.oninput=()=>formItems[+el.dataset.itemName].name=el.value);document.querySelectorAll('[data-item-price]').forEach(el=>el.oninput=()=>formItems[+el.dataset.itemPrice].amount=el.value===''?null:Number(el.value));document.querySelectorAll('[data-remove-item]').forEach(el=>el.onclick=()=>{formItems.splice(+el.dataset.removeItem,1);renderItems()})}
    function updateTotal(){const subtotal=Number(document.querySelector('#newAmount').value)||0,total=subtotal*(1+formTip/100);document.querySelector('#totalPreview').textContent='服務費 '+money(subtotal*formTip/100)+'・總計 '+money(Math.round(total*100)/100)}
    function openTransaction(id=null){editingId=id;const x=id?transactions.find(t=>t.id===id):null;formType=x?.type||'expense';formCategory=x?.category||'食物';formTip=x?.tipPercent||0;formItems=(x?.items||[]).map(i=>({...i}));document.querySelector('#transactionSheetTitle').textContent=x?'編輯交易':'新增交易';document.querySelector('#newName').value=x?.name||'';document.querySelector('#newAmount').value=x?.subtotal??x?.amount??'';document.querySelector('#newPayment').value=x?.payment||'Chase帳戶';document.querySelector('#accountValue').textContent=document.querySelector('#newPayment').value;document.querySelector('#newDate').value=x?.date||todayKey();document.querySelector('#newDateDisplay').textContent=displayDate(document.querySelector('#newDate').value);document.querySelector('#newNote').value=x?.note||'';document.querySelectorAll('.type-toggle button').forEach(b=>b.classList.toggle('active',b.dataset.type===formType));document.querySelectorAll('#tipChips button').forEach(b=>b.classList.toggle('active',+b.dataset.tip===formTip));renderCategories();renderSuggestions();renderItems();updateTotal();openPanel(document.querySelector('#addSheet'))}
    function closeAccountPicker(){document.querySelector('#pickerBackdrop').classList.remove('open');document.querySelector('#accountSheet').classList.remove('open')}
    function renderAccounts(){const current=document.querySelector('#newPayment').value;document.querySelector('#accountChoices').innerHTML=['Chase帳戶','Chase信用卡','現金'].map(name=>'<button class="account-choice '+(name===current?'active':'')+'" data-account-choice="'+escapeHTML(name)+'"><span>'+escapeHTML(name)+'</span><span class="check">✓</span></button>').join('');document.querySelectorAll('[data-account-choice]').forEach(button=>button.onclick=()=>{document.querySelector('#newPayment').value=button.dataset.accountChoice;document.querySelector('#accountValue').textContent=button.dataset.accountChoice;closeAccountPicker()})}
    function closePanels(){closeAccountPicker();pop.classList.remove('open');filterPanel.classList.remove('open');document.querySelector('#customEditor').hidden=true;document.querySelector('#addSheet').classList.remove('open');back.classList.remove('open')}
    function openPanel(el){closePanels();el.classList.add('open');back.classList.add('open')}
    document.querySelectorAll('.summary-card').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;categoryFilter=null;document.querySelectorAll('.summary-card').forEach(x=>x.classList.toggle('active',x===b));render()});
    document.querySelectorAll('.seg button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;if(tab==='category')categoryFilter=null;seg.dataset.tab=tab;render()});
    document.querySelector('#calendar').onclick=()=>openPanel(pop);document.querySelector('#currentRange').onclick=()=>openPanel(pop);back.onclick=closePanels;
    document.querySelectorAll('.range-btn').forEach(b=>b.onclick=()=>{if(b.dataset.period==='custom'){const {start,end}=activeRange();document.querySelector('#customStart').value=keyOf(start);document.querySelector('#customEnd').value=keyOf(end);document.querySelector('#customEditor').hidden=false;return}period=b.dataset.period;closePanels();render();toast(`${b.textContent}區間已套用`)});
    document.querySelector('#applyCustom').onclick=()=>{const start=dateFromKey(document.querySelector('#customStart').value),end=dateFromKey(document.querySelector('#customEnd').value);if(Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<start){toast('請選擇有效的起訖日期');return}customRange={start,end};period='custom';anchorDate=start;closePanels();render();toast('自訂區間已套用')};
    document.querySelector('#prev').onclick=()=>{shiftRange(-1);render()};document.querySelector('#next').onclick=()=>{shiftRange(1);render()};
    document.querySelector('#todayRange').onclick=()=>{const today=dateFromKey(todayKey());if(period==='custom'){const {start,end}=activeRange(),span=Math.round((end-start)/86400000)+1;customRange={start:addDays(today,1-span),end:today};anchorDate=today}else anchorDate=today;render();toast('已回到今天所在區間')};
    document.querySelector('#filter').onclick=()=>{pendingPayment=paymentFilter;document.querySelectorAll('.filter-option').forEach(x=>x.classList.toggle('active',x.dataset.payment===pendingPayment));openPanel(filterPanel)};document.querySelectorAll('.filter-option').forEach(b=>b.onclick=()=>{pendingPayment=b.dataset.payment;document.querySelectorAll('.filter-option').forEach(x=>x.classList.toggle('active',x===b))});document.querySelector('#clearFilter').onclick=()=>{pendingPayment='all';document.querySelectorAll('.filter-option').forEach(x=>x.classList.toggle('active',x.dataset.payment==='all'))};document.querySelector('#applyFilter').onclick=()=>{paymentFilter=pendingPayment;closePanels();render();toast(paymentFilter==='all'?'已顯示全部帳戶':`已篩選 ${paymentFilter}`)};
    function searchText(x){return [x.name,x.category,x.payment,x.note,x.date,x.type==='income'?'收入':'支出',x.subtotal??x.amount,x.tipPercent,x.tipAmount,x.amount,...(x.items||[]).flatMap(item=>[item.name,item.amount])].filter(value=>value!==undefined&&value!==null).join(' ').toLocaleLowerCase('zh-Hant')}
    function searchResults(q){const target=document.querySelector('#searchResults'),heading=document.querySelector('#searchHeading'),query=q.trim().toLocaleLowerCase('zh-Hant');if(!query){heading.textContent='最近的搜尋';target.innerHTML='<p>輸入名稱、分類、帳戶或備註搜尋</p>';return}const categoryHits=categoryNames.filter(name=>name.toLocaleLowerCase('zh-Hant').includes(query));const found=transactions.filter(x=>searchText(x).includes(query));heading.textContent=`搜尋結果（${found.length} 筆交易）`;target.innerHTML=(categoryHits.length?'<div style="display:grid;gap:7px;margin-bottom:14px">'+categoryHits.map(name=>'<button class="search-category-result" data-search-category="'+escapeHTML(name)+'"><span>分類：'+escapeHTML(name)+'</span><span>查看明細 ›</span></button>').join('')+'</div>':'')+found.map(x=>`<button class="search-result" data-search-tx="${x.id}">${escapeHTML(x.name)}<small>${escapeHTML(x.category)}・${escapeHTML(x.payment)}・${x.date}　${x.type==='income'?'+':'-'}${money(x.amount)}${x.note?'・備註':''}${x.items?.length?'・'+x.items.length+' 項商品':''}</small></button>`).join('')||(!categoryHits.length?'<p style="color:var(--muted);font-weight:700">找不到符合的交易</p>':'');document.querySelectorAll('[data-search-category]').forEach(button=>button.onclick=()=>{mode='expense';categoryFilter=button.dataset.searchCategory;tab='detail';document.querySelector('#searchPage').classList.remove('open');document.querySelectorAll('.summary-card').forEach(card=>card.classList.toggle('active',card.dataset.mode===mode));render()});document.querySelectorAll('[data-search-tx]').forEach(button=>button.onclick=()=>{document.querySelector('#searchPage').classList.remove('open');openTransaction(button.dataset.searchTx)})}
    document.querySelector('#search').onclick=()=>{document.querySelector('#searchPage').classList.add('open');setTimeout(()=>document.querySelector('#searchInput').focus(),50)};document.querySelector('#searchInput').oninput=e=>searchResults(e.target.value);document.querySelector('#closeSearch').onclick=()=>document.querySelector('#searchPage').classList.remove('open');document.querySelector('#clearSearch').onclick=()=>{document.querySelector('#searchInput').value='';searchResults('')};
    document.querySelector('#export').onclick=()=>{const csv=['日期,類型,分類,描述,帳戶,金額',...selected().map(x=>[x.date,x.type==='income'?'收入':'支出',x.category,x.name,x.payment,x.amount].join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));a.download='收支表_2026.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV 已匯出')};
    document.querySelector('#fab').onclick=()=>openTransaction();document.querySelector('#cancelTransaction').onclick=closePanels;document.querySelector('#newName').oninput=renderSuggestions;document.querySelector('#newAmount').oninput=()=>{updateTotal();renderSuggestions()};document.querySelector('#newPayment').onchange=e=>document.querySelector('#accountValue').textContent=e.target.value;document.querySelector('#accountControl').onclick=()=>{renderAccounts();document.querySelector('#pickerBackdrop').classList.add('open');document.querySelector('#accountSheet').classList.add('open')};document.querySelector('#pickerBackdrop').onclick=closeAccountPicker;document.querySelector('#cancelAccount').onclick=closeAccountPicker;const dateInput=document.querySelector('#newDate');document.querySelector('.native-date-field').onclick=()=>{try{dateInput.showPicker?.()}catch{dateInput.focus();dateInput.click()}};dateInput.onchange=e=>document.querySelector('#newDateDisplay').textContent=displayDate(e.target.value);document.querySelector('#addItem').onclick=()=>{formItems.push({name:'',amount:null});renderItems()};document.querySelectorAll('.type-toggle button').forEach(b=>b.onclick=()=>{formType=b.dataset.type;document.querySelectorAll('.type-toggle button').forEach(x=>x.classList.toggle('active',x===b));renderSuggestions()});document.querySelectorAll('#tipChips button').forEach(b=>b.onclick=()=>{formTip=+b.dataset.tip;document.querySelectorAll('#tipChips button').forEach(x=>x.classList.toggle('active',x===b));updateTotal()});document.querySelector('#saveTransaction').onclick=()=>{const name=document.querySelector('#newName').value.trim(),subtotal=Number(document.querySelector('#newAmount').value),date=document.querySelector('#newDate').value,payment=document.querySelector('#newPayment').value;if(!name||!subtotal||!date){toast('請填寫名稱、小計與日期');return}const tx={id:editingId||Date.now(),date,type:formType,category:formType==='income'?'收入':formCategory,name,payment,subtotal,tipPercent:formTip,tipAmount:Math.round(subtotal*formTip)/100,amount:Math.round(subtotal*(1+formTip/100)*100)/100,items:formItems.filter(i=>i.name.trim()),note:document.querySelector('#newNote').value.trim()};if(editingId)transactions=transactions.map(x=>x.id===editingId?tx:x);else transactions.push(tx);anchorDate=dateFromKey(date);period='month';closePanels();render();toast(editingId?'交易已更新':'交易已新增')};
    function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.t);window.t=setTimeout(()=>e.classList.remove('show'),1600)}
    document.querySelector('#light').onclick=()=>{document.documentElement.dataset.theme='';document.querySelector('#light').classList.add('active');document.querySelector('#dark').classList.remove('active')};document.querySelector('#dark').onclick=()=>{document.documentElement.dataset.theme='dark';document.querySelector('#dark').classList.add('active');document.querySelector('#light').classList.remove('active')};render();
  